<?xml version='1.0' encoding='utf-8'?>
<interface version="1.0">
  <object class="tk.Toplevel" id="toplevel_1">
    <property name="height">200</property>
    <property name="width">200</property>
    <child>
      <object class="tk.Frame" id="frame_1">
        <property name="height">200</property>
        <property name="width">200</property>
        <layout manager="pack">
          <property name="propagate">True</property>
          <property name="side">top</property>
        </layout>
        <child>
          <object class="tk.Label" id="label_hello">
            <property name="text" translatable="yes">Hello
Generated by pygubu-designer</property>
            <layout manager="pack">
              <property name="padx">8</property>
              <property name="pady">8</property>
              <property name="propagate">True</property>
              <property name="side">top</property>
            </layout>
          </object>
        </child>
        <child>
          <object class="tk.Button" id="button_ok">
            <property name="command">on_button_clicked</property>
            <property name="text" translatable="yes">OK</property>
            <layout manager="pack">
              <property name="propagate">True</property>
              <property name="side">top</property>
            </layout>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
