import os
import tkinter as tk
import tkinter.ttk as ttk
import pygubu

PROJECT_PATH = os.path.abspath(os.path.dirname(__file__))
PROJECT_UI = os.path.join(PROJECT_PATH, "hello.ui")

class HelloApp:
    def __init__(self, master=None):
        # build ui
        self.main = tk.Tk() if master is None else tk.Toplevel(master)
        self.frame01 = ttk.Frame(self.main)
        self.label_1 = ttk.Label(self.frame01)
        self.label_1.configure(foreground='#ff0000', justify='center', padding='33', relief='ridge')
        self.label_1.configure(text='Hello')
        self.label_1.grid(padx='8', pady='8')
        self.label_2 = ttk.Label(self.frame01)
        self.label_2.configure(justify='center', text='Generated by pygubu-designer')
        self.label_2.grid(padx='22', pady='4', row='1')
        self.button_ok = ttk.Button(self.frame01)
        self.button_ok.configure(text='Ok')
        self.button_ok.grid(ipadx='4', padx='8', pady='12', row='2')
        self.button_ok.configure(command=self.on_ok_clicked)
        self.frame01.configure(height='200', padding='12', width='200')
        self.frame01.pack(side='top')
        self.main.configure(height='200', width='200')
        self.main.title('Hello')

        # Main widget
        self.mainwindow = self.main
    
    def on_ok_clicked(self):
        pass

    def run(self):
        self.mainwindow.mainloop()


if __name__ == '__main__':
    app = HelloApp()
    app.run()


